"use client";
import { Provider } from "react-redux";
import localFont from "next/font/local";
import "./globals.css";
import store from "./store/store"; // Adjust the path to your Redux store

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap the app with Redux Provider */}
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
